### ISSUE TITLE
Keynote 版で、特定のテンプレートの箇条書きリストから Tab を押すとクラッシュする

### ISSUE THREAD

**Issue by qsona** [sanographix/azusa3#1]
## 概要

以下の手順により、Keynote がクラッシュ (強制終了) してしまう

- Keynote に Azusa 3 をインストール、それを利用して新規ファイル作成
- Heading & Body でスライド追加 (Light Heading & Body も同様)
- 箇条書きのとこにカーソルを置いて Tab キーを押す

## 環境

- Keynote version 14.0 (7039.0.94)
- macOS 13.4 (22F66)

## その他

- 同じようでも、Background Image & Body のテンプレートを使って同様の操作をしたときはクラッシュしない
- Heading & Body のスライドの箇条書きリストが含まれているエリアをコピーして他のスライドに貼り付けて Tab を押してもクラッシュしない
- 以前は問題なかったので、Keynote のどこかのバージョンから起きているものと思います
- その他の深い調査はできていません (バージョン違いで試すなど) 一旦ご報告まで... 🙇

**Comment by sanographix** [comment]
@qsona ご報告ありがとうございます。手元のKeynote v14.0 / macOS 13.6 でも同様に再現しました。(不思議なエラーですね... )

理由は不明ですが、「箇条書きとリスト」のリストスタイル設定に何らかの齟齬が発生していたようです。再度マスタースライドで該当箇所を設定しなおしたところ解決しました。
先ほど `v3.1` を作成したので、お手元で試していただけますか。

https://github.com/sanographix/azusa3/archive/v3.1.zip

Keynote右ペインの「リストスタイル」が「複数」と表示されるのが旧バージョン、「行頭記号」となっているのが新バージョンです。

|v3.0.2|v3.1|
|-|-|
|<img width="278" alt="1000" src="https://github.com/sanographix/azusa3/assets/1533421/c46a46ed-25c2-4f2f-9b98-8da431f3442d">|<img width="324" alt="スクリーンショット 2024-04-19 21 59 26" src="https://github.com/sanographix/azusa3/assets/1533421/27c1a6c9-1525-481e-9f41-1fb0bce1d598">|
